version: '2'
services:
    ratingsystem-app:
        image: ratingsystem
        environment:
            # - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://ratingsystem-postgresql:5432/RatingSystem
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
            - SPRING_DATA_ELASTICSEARCH_CLUSTER_NODES=ratingsystem-elasticsearch:9300
        ports:
            - 8080:8080
    ratingsystem-postgresql:
        extends:
            file: postgresql.yml
            service: ratingsystem-postgresql
    ratingsystem-elasticsearch:
        extends:
            file: elasticsearch.yml
            service: ratingsystem-elasticsearch
